"""
Endpoints for retrieving results of background tasks (AI and PDF generation).
"""

from celery.result import AsyncResult
from flask import Blueprint, Response, jsonify, make_response, send_file, url_for

from tasks import celery_app

tasks_bp = Blueprint("tasks", __name__, url_prefix="/tasks")


def pdf_response(result: dict) -> Response:
    """Return a PDF file for eager results or a 202 queued response."""
    if result["ready"]:
        payload = result["result"]
        if "error" in payload:
            return make_response(payload["error"], payload["status_code"])
        return send_file(
            payload["path"],
            download_name=payload["download_name"],
            mimetype="application/pdf",
        )
    return make_response(
        jsonify(
            {
                "status": "queued",
                "task_id": result["task_id"],
                "download_url": url_for("tasks.download_pdf", task_id=result["task_id"]),
            }
        ),
        202,
    )


@tasks_bp.route("/result/<task_id>")
def task_result(task_id: str) -> Response:
    """
    Return the result of an AI generation task or its current status.

    Args:
        task_id: Celery task identifier.

    Returns:
        JSON with the result when ready, or a 202 status while processing.
    """
    result = AsyncResult(task_id, app=celery_app)
    try:
        value = result.get(timeout=1, propagate=False)
    except TimeoutError:
        return jsonify({"status": "processing", "task_id": task_id}), 202

    if isinstance(value, Exception):
        return jsonify({"status": "failed", "task_id": task_id, "error": str(value)}), 500

    return jsonify({"status": "ready", "task_id": task_id, "result": value}), 200


@tasks_bp.route("/download-pdf/<task_id>")
def download_pdf(task_id: str) -> Response:
    """
    Download a PDF generated by the background task queue.

    Args:
        task_id: Celery task identifier for the PDF generation task.

    Returns:
        The PDF file when ready, or a 202 status while processing.
    """
    result = AsyncResult(task_id, app=celery_app)
    try:
        value = result.get(timeout=1, propagate=False)
    except TimeoutError:
        return jsonify({"status": "processing", "task_id": task_id}), 202

    if isinstance(value, Exception):
        return jsonify({"status": "failed", "task_id": task_id, "error": str(value)}), 500

    path = value.get("path")
    download_name = value.get("download_name", "document.pdf")
    return send_file(path, download_name=download_name, mimetype="application/pdf")
