"""Normalize JSON columns into related tables

Revision ID: 2f1ab9d0aed0
Revises: 
Create Date: 2026-07-09 18:31:52.137959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1ab9d0aed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('departments_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departments_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('departments_id'),
    sa.UniqueConstraint('departments_name')
    )
    op.create_table('login_attempts',
    sa.Column('login_attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_attempt_ip_address', sa.String(length=45), nullable=False),
    sa.Column('login_attempt_count', sa.Integer(), nullable=False),
    sa.Column('login_attempt_last_attempt_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('login_attempt_id')
    )
    op.create_table('personnel_in_charge_forms',
    sa.Column('personnel_in_charge_forms_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_in_charge_forms_name', sa.String(length=255), nullable=False),
    sa.Column('personnel_in_charge_forms_position', sa.String(length=255), nullable=False),
    sa.Column('personnel_in_charge_forms_department', sa.String(length=255), nullable=False),
    sa.Column('personnel_in_charge_forms_contact_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('personnel_in_charge_forms_id')
    )
    op.create_table('signatories',
    sa.Column('signatory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signatory_title', sa.String(length=50), nullable=False),
    sa.Column('signatory_first_name', sa.String(length=50), nullable=False),
    sa.Column('signatory_middle_name', sa.String(length=50), nullable=True),
    sa.Column('signatory_last_name', sa.String(length=50), nullable=False),
    sa.Column('signatory_suffix', sa.String(length=50), nullable=True),
    sa.Column('signatory_position', sa.String(length=100), nullable=False),
    sa.Column('signatory_department', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('signatory_id')
    )
    op.create_table('student_organizations',
    sa.Column('student_organizations_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_organizations_name', sa.String(length=255), nullable=False),
    sa.Column('student_organizations_financial_bank_book_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('student_organizations_id')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_picture', sa.JSON(), nullable=False),
    sa.Column('users_title', sa.String(length=50), nullable=True),
    sa.Column('users_first_name', sa.String(length=50), nullable=False),
    sa.Column('users_middle_name', sa.String(length=50), nullable=True),
    sa.Column('users_last_name', sa.String(length=50), nullable=False),
    sa.Column('users_suffix', sa.String(length=50), nullable=True),
    sa.Column('users_username', sa.String(length=50), nullable=False),
    sa.Column('users_email', sa.String(length=100), nullable=False),
    sa.Column('users_departments_id', sa.Integer(), nullable=False),
    sa.Column('users_role', sa.Enum('Student Council Officer', 'Faculty', 'Staff', 'Admin', name='role_enum'), nullable=False),
    sa.Column('users_student_organization', sa.Integer(), nullable=True),
    sa.Column('users_student_organization_position', sa.Enum('President', 'Vice President', 'Secretary', 'Treasurer', 'Auditor', 'Business Manager', 'Public Relations Officer', '1st Year IT Representative', '1st Year CS Representative', '2nd Year IT Representative', '2nd Year CS Representative', '3rd Year IT Representative', '3rd Year CS Representative', '4th Year IT Representative', '4th Year CS Representative', name='position_enum'), nullable=True),
    sa.Column('users_home_address', sa.String(length=255), nullable=True),
    sa.Column('users_contact_number', sa.String(length=20), nullable=True),
    sa.Column('signature', sa.JSON(), nullable=False),
    sa.Column('users_password', sa.String(length=255), nullable=False),
    sa.Column('users_email_verified', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_departments_id'], ['departments.departments_id'], ),
    sa.ForeignKeyConstraint(['users_student_organization'], ['student_organizations.student_organizations_id'], ),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('users_email'),
    sa.UniqueConstraint('users_username')
    )
    op.create_table('concept_paper_forms',
    sa.Column('concept_paper_forms_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_paper_forms_semester', sa.String(length=50), nullable=True),
    sa.Column('concept_paper_forms_academic_year', sa.String(length=50), nullable=True),
    sa.Column('concept_paper_forms_status', sa.String(length=50), nullable=True),
    sa.Column('concept_paper_forms_departments_id', sa.Integer(), nullable=True),
    sa.Column('concept_paper_forms_endorsed_by', sa.Integer(), nullable=True),
    sa.Column('concept_paper_forms_recommending_approval_by', sa.Integer(), nullable=True),
    sa.Column('concept_paper_forms_approved_by', sa.Integer(), nullable=True),
    sa.Column('concept_paper_forms_subject', sa.String(length=255), nullable=True),
    sa.Column('concept_paper_forms_date', sa.Date(), nullable=True),
    sa.Column('concept_paper_forms_body', sa.Text(), nullable=True),
    sa.Column('concept_paper_forms_event_start_date_and_time', sa.DateTime(), nullable=True),
    sa.Column('concept_paper_forms_event_end_date_and_time', sa.DateTime(), nullable=True),
    sa.Column('concept_paper_forms_location', sa.String(length=255), nullable=True),
    sa.Column('concept_paper_forms_participants', sa.String(length=255), nullable=True),
    sa.Column('concept_paper_forms_budget', sa.String(length=255), nullable=True),
    sa.Column('concept_paper_forms_descriptions', sa.Text(), nullable=True),
    sa.Column('concept_paper_forms_expected_number_of_participants', sa.Text(), nullable=True),
    sa.Column('concept_paper_forms_prepared_by', sa.Integer(), nullable=True),
    sa.Column('concept_paper_forms_signed_and_reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_paper_forms_approved_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['concept_paper_forms_departments_id'], ['departments.departments_id'], ),
    sa.ForeignKeyConstraint(['concept_paper_forms_endorsed_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['concept_paper_forms_prepared_by'], ['users.users_id'], ),
    sa.ForeignKeyConstraint(['concept_paper_forms_recommending_approval_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['concept_paper_forms_signed_and_reviewed_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('concept_paper_forms_id')
    )
    op.create_table('email_verification',
    sa.Column('email_verification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_verification_users_id', sa.Integer(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=False),
    sa.Column('email_verification_new_email', sa.String(length=100), nullable=False),
    sa.Column('email_verification_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_verification_users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('email_verification_id')
    )
    op.create_table('minutes_of_the_meeting',
    sa.Column('minutes_of_the_meeting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('minutes_of_the_meeting_date', sa.DateTime(), nullable=False),
    sa.Column('minutes_of_the_meeting_semester', sa.String(length=50), nullable=False),
    sa.Column('minutes_of_the_meeting_academic_year', sa.String(length=50), nullable=False),
    sa.Column('minutes_of_the_meeting_status', sa.String(length=50), nullable=False),
    sa.Column('minutes_of_the_meeting_departments_id', sa.Integer(), nullable=True),
    sa.Column('minutes_of_the_meeting_presiding_officer', sa.String(length=100), nullable=False),
    sa.Column('minutes_of_the_meeting_agenda', sa.Text(), nullable=False),
    sa.Column('minutes_of_the_meeting_notes', sa.Text(), nullable=True),
    sa.Column('minutes_of_the_meeting_adjourned', sa.DateTime(), nullable=True),
    sa.Column('minutes_of_the_meeting_approved_by', sa.Integer(), nullable=True),
    sa.Column('minutes_of_the_meeting_prepared_by', sa.Integer(), nullable=True),
    sa.Column('minutes_of_the_meeting_noted_by', sa.Integer(), nullable=True),
    sa.Column('photo_documentation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['minutes_of_the_meeting_approved_by'], ['users.users_id'], ),
    sa.ForeignKeyConstraint(['minutes_of_the_meeting_departments_id'], ['departments.departments_id'], ),
    sa.ForeignKeyConstraint(['minutes_of_the_meeting_noted_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['minutes_of_the_meeting_prepared_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('minutes_of_the_meeting_id')
    )
    op.create_table('password_reset',
    sa.Column('password_reset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password_reset_users_id', sa.Integer(), nullable=False),
    sa.Column('password_reset_selector', sa.String(length=255), nullable=False),
    sa.Column('password_reset_token', sa.String(length=255), nullable=False),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['password_reset_users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('password_reset_id')
    )
    op.create_table('activity_report_forms',
    sa.Column('activity_report_forms_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_report_forms_concept_paper_forms_id', sa.Integer(), nullable=True),
    sa.Column('activity_report_forms_nature_of_the_activity', sa.String(length=255), nullable=True),
    sa.Column('activity_report_forms_personnel_in_charge_forms_id', sa.Integer(), nullable=True),
    sa.Column('activity_report_forms_contact_numbers', sa.String(length=255), nullable=True),
    sa.Column('activity_report_forms_prepared_by', sa.Integer(), nullable=True),
    sa.Column('activity_report_forms_noted_by', sa.Integer(), nullable=True),
    sa.Column('activity_report_date_submission', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['activity_report_forms_concept_paper_forms_id'], ['concept_paper_forms.concept_paper_forms_id'], ),
    sa.ForeignKeyConstraint(['activity_report_forms_noted_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['activity_report_forms_personnel_in_charge_forms_id'], ['personnel_in_charge_forms.personnel_in_charge_forms_id'], ),
    sa.ForeignKeyConstraint(['activity_report_forms_prepared_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('activity_report_forms_id')
    )
    op.create_table('events',
    sa.Column('events_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('events_concept_paper_forms_id', sa.Integer(), nullable=True),
    sa.Column('events_name', sa.String(length=255), nullable=True),
    sa.Column('events_semester', sa.String(length=50), nullable=False),
    sa.Column('events_academic_year', sa.String(length=50), nullable=False),
    sa.Column('events_start_date_and_time', sa.DateTime(), nullable=True),
    sa.Column('events_end_date_and_time', sa.DateTime(), nullable=True),
    sa.Column('events_venue', sa.String(length=255), nullable=True),
    sa.Column('events_budget', sa.String(length=255), nullable=True),
    sa.Column('events_status', sa.String(length=50), nullable=True),
    sa.Column('events_description', sa.Text(), nullable=True),
    sa.Column('events_remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['events_concept_paper_forms_id'], ['concept_paper_forms.concept_paper_forms_id'], ),
    sa.PrimaryKeyConstraint('events_id')
    )
    op.create_table('excuse_letter_forms',
    sa.Column('excuse_letter_forms_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('excuse_letter_forms_concept_paper_forms_id', sa.Integer(), nullable=True),
    sa.Column('excuse_letter_forms_department_office_unit', sa.String(length=255), nullable=True),
    sa.Column('excuse_letter_forms_personnel_in_charge_forms_id', sa.Integer(), nullable=True),
    sa.Column('excuse_letter_forms_dean', sa.Integer(), nullable=True),
    sa.Column('excuse_letter_forms_noted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['excuse_letter_forms_concept_paper_forms_id'], ['concept_paper_forms.concept_paper_forms_id'], ),
    sa.ForeignKeyConstraint(['excuse_letter_forms_dean'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['excuse_letter_forms_noted_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['excuse_letter_forms_personnel_in_charge_forms_id'], ['signatories.signatory_id'], ),
    sa.PrimaryKeyConstraint('excuse_letter_forms_id')
    )
    op.create_table('learning_journal_forms',
    sa.Column('learning_journal_forms_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learning_journal_forms_concept_paper_forms_id', sa.Integer(), nullable=True),
    sa.Column('learning_journal_forms_name', sa.String(length=255), nullable=False),
    sa.Column('learning_journal_forms_date', sa.Date(), nullable=False),
    sa.Column('learning_journal_forms_time', sa.Time(), nullable=False),
    sa.Column('learning_journal_forms_location', sa.String(length=255), nullable=False),
    sa.Column('learning_journal_forms_activity', sa.String(length=255), nullable=False),
    sa.Column('learning_journal_forms_role', sa.String(length=255), nullable=False),
    sa.Column('learning_journal_forms_prepared_by', sa.Integer(), nullable=True),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('learnings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['learning_journal_forms_concept_paper_forms_id'], ['concept_paper_forms.concept_paper_forms_id'], ),
    sa.ForeignKeyConstraint(['learning_journal_forms_prepared_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('learning_journal_forms_id')
    )
    op.create_table('learning_outcomes',
    sa.Column('learning_outcome_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_paper_forms_id', sa.Integer(), nullable=False),
    sa.Column('learning_outcome_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['concept_paper_forms_id'], ['concept_paper_forms.concept_paper_forms_id'], ),
    sa.PrimaryKeyConstraint('learning_outcome_id')
    )
    op.create_table('meeting_attendees',
    sa.Column('meeting_attendee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('minutes_of_the_meeting_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['minutes_of_the_meeting_id'], ['minutes_of_the_meeting.minutes_of_the_meeting_id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('meeting_attendee_id')
    )
    op.create_table('objectives',
    sa.Column('objective_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_paper_forms_id', sa.Integer(), nullable=False),
    sa.Column('objective_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['concept_paper_forms_id'], ['concept_paper_forms.concept_paper_forms_id'], ),
    sa.PrimaryKeyConstraint('objective_id')
    )
    op.create_table('parent_guardian_consent_forms',
    sa.Column('parent_guardian_consent_forms_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_guardian_consent_forms_concept_paper_forms_id', sa.Integer(), nullable=True),
    sa.Column('parent_guardian_consent_forms_parent_guardian_name', sa.String(length=255), nullable=False),
    sa.Column('parent_guardian_consent_forms_parent_guardian_contact_number', sa.String(length=20), nullable=False),
    sa.Column('parent_guardian_consent_forms_parent_guardian_address', sa.String(length=255), nullable=False),
    sa.Column('parent_guardian_consent_forms_parent_guardian_relationship', sa.String(length=255), nullable=False),
    sa.Column('parent_guardian_consent_forms_student_name', sa.String(length=255), nullable=False),
    sa.Column('parent_guardian_consent_forms_student_year_and_section', sa.String(length=255), nullable=False),
    sa.Column('parent_guardian_consent_forms_student_contact_number', sa.String(length=20), nullable=False),
    sa.Column('parent_guardian_consent_forms_consent', sa.String(length=10), nullable=False),
    sa.Column('parent_guardian_consent_forms_date', sa.Date(), nullable=False),
    sa.Column('parent_guardian_consent_forms_signature', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_guardian_consent_forms_concept_paper_forms_id'], ['concept_paper_forms.concept_paper_forms_id'], ),
    sa.PrimaryKeyConstraint('parent_guardian_consent_forms_id')
    )
    op.create_table('board_resolutions',
    sa.Column('board_resolutions_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_resolutions_date', sa.DateTime(), nullable=True),
    sa.Column('board_resolutions_events_id', sa.Integer(), nullable=True),
    sa.Column('board_resolutions_departments_id', sa.Integer(), nullable=True),
    sa.Column('board_resolutions_title', sa.String(length=255), nullable=True),
    sa.Column('board_resolutions_academic_year', sa.String(length=50), nullable=True),
    sa.Column('board_resolutions_semester', sa.String(length=50), nullable=True),
    sa.Column('board_resolutions_status', sa.String(length=50), nullable=True),
    sa.Column('board_resolutions_total_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('board_resolutions_description', sa.Text(), nullable=True),
    sa.Column('board_resolutions_prepared_by', sa.Integer(), nullable=True),
    sa.Column('board_resolutions_approved_by', sa.Integer(), nullable=True),
    sa.Column('student_signatory_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['board_resolutions_approved_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['board_resolutions_departments_id'], ['departments.departments_id'], ),
    sa.ForeignKeyConstraint(['board_resolutions_events_id'], ['events.events_id'], ),
    sa.ForeignKeyConstraint(['board_resolutions_prepared_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('board_resolutions_id')
    )
    op.create_table('departments_events',
    sa.Column('departments_id', sa.Integer(), nullable=False),
    sa.Column('events_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departments_id'], ['departments.departments_id'], ),
    sa.ForeignKeyConstraint(['events_id'], ['events.events_id'], ),
    sa.PrimaryKeyConstraint('departments_id', 'events_id')
    )
    op.create_table('documentation',
    sa.Column('documentation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documentation_events_id', sa.Integer(), nullable=True),
    sa.Column('documentation_academic_year', sa.String(length=50), nullable=True),
    sa.Column('documentation_semester', sa.String(length=50), nullable=True),
    sa.Column('documentation_status', sa.String(length=50), nullable=True),
    sa.Column('documentation_departments_id', sa.Integer(), nullable=True),
    sa.Column('documentation_type', sa.String(length=50), nullable=True),
    sa.Column('documentation_activity_report_forms_id', sa.Integer(), nullable=True),
    sa.Column('documentation_prepared_by', sa.Integer(), nullable=True),
    sa.Column('documentation_learning_journal_forms_id', sa.Integer(), nullable=True),
    sa.Column('documentation_checked_by', sa.Integer(), nullable=True),
    sa.Column('documentation_noted_by', sa.Integer(), nullable=True),
    sa.Column('documentation_date_of_submission', sa.DateTime(), nullable=True),
    sa.Column('documentation_rating', sa.Float(), nullable=True),
    sa.Column('documentation_comments_suggestions', sa.Text(), nullable=True),
    sa.Column('evaluation_images', sa.JSON(), nullable=False),
    sa.Column('attendance_images', sa.JSON(), nullable=False),
    sa.Column('evaluation_student_names', sa.JSON(), nullable=False),
    sa.Column('event_photo_images', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['documentation_activity_report_forms_id'], ['activity_report_forms.activity_report_forms_id'], ),
    sa.ForeignKeyConstraint(['documentation_checked_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['documentation_departments_id'], ['departments.departments_id'], ),
    sa.ForeignKeyConstraint(['documentation_events_id'], ['events.events_id'], ),
    sa.ForeignKeyConstraint(['documentation_learning_journal_forms_id'], ['learning_journal_forms.learning_journal_forms_id'], ),
    sa.ForeignKeyConstraint(['documentation_noted_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['documentation_prepared_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('documentation_id')
    )
    op.create_table('event_invitations',
    sa.Column('event_invitations_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_invitations_events_id', sa.Integer(), nullable=False),
    sa.Column('event_invitations_email', sa.String(length=255), nullable=False),
    sa.Column('event_invitations_token', sa.String(length=64), nullable=False),
    sa.Column('event_invitations_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_invitations_events_id'], ['events.events_id'], ),
    sa.PrimaryKeyConstraint('event_invitations_id')
    )
    op.create_table('financial_reports',
    sa.Column('financial_reports_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_reports_date', sa.DateTime(), nullable=False),
    sa.Column('financial_reports_academic_year', sa.String(length=50), nullable=False),
    sa.Column('financial_reports_semester', sa.String(length=50), nullable=False),
    sa.Column('financial_reports_status', sa.String(length=50), nullable=False),
    sa.Column('financial_reports_events_id', sa.Integer(), nullable=True),
    sa.Column('financial_reports_departments_id', sa.Integer(), nullable=True),
    sa.Column('financial_reports_title', sa.String(length=255), nullable=False),
    sa.Column('financial_reports_audited_and_prepared_by', sa.Integer(), nullable=True),
    sa.Column('financial_reports_noted_by', sa.Integer(), nullable=True),
    sa.Column('financial_reports_recommending_approval_by', sa.Integer(), nullable=True),
    sa.Column('financial_reports_approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['financial_reports_approved_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['financial_reports_audited_and_prepared_by'], ['users.users_id'], ),
    sa.ForeignKeyConstraint(['financial_reports_departments_id'], ['departments.departments_id'], ),
    sa.ForeignKeyConstraint(['financial_reports_events_id'], ['events.events_id'], ),
    sa.ForeignKeyConstraint(['financial_reports_noted_by'], ['signatories.signatory_id'], ),
    sa.ForeignKeyConstraint(['financial_reports_recommending_approval_by'], ['signatories.signatory_id'], ),
    sa.PrimaryKeyConstraint('financial_reports_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('events_id', sa.Integer(), nullable=False),
    sa.Column('transaction_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('unit_amount', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('receipt_public_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['events_id'], ['events.events_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('activity_report_items',
    sa.Column('activity_report_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_report_forms_id', sa.Integer(), nullable=True),
    sa.Column('documentation_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['activity_report_forms_id'], ['activity_report_forms.activity_report_forms_id'], ),
    sa.ForeignKeyConstraint(['documentation_id'], ['documentation.documentation_id'], ),
    sa.PrimaryKeyConstraint('activity_report_item_id')
    )
    op.create_table('evaluation_forms',
    sa.Column('evaluation_form_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documentation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['documentation_id'], ['documentation.documentation_id'], ),
    sa.PrimaryKeyConstraint('evaluation_form_id')
    )
    op.create_table('tally_items',
    sa.Column('tally_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documentation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extremely_satisfied', sa.Integer(), nullable=False),
    sa.Column('satisfied', sa.Integer(), nullable=False),
    sa.Column('neutral', sa.Integer(), nullable=False),
    sa.Column('dissatisfied', sa.Integer(), nullable=False),
    sa.Column('extremely_dissatisfied', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documentation_id'], ['documentation.documentation_id'], ),
    sa.PrimaryKeyConstraint('tally_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tally_items')
    op.drop_table('evaluation_forms')
    op.drop_table('activity_report_items')
    op.drop_table('transactions')
    op.drop_table('financial_reports')
    op.drop_table('event_invitations')
    op.drop_table('documentation')
    op.drop_table('departments_events')
    op.drop_table('board_resolutions')
    op.drop_table('parent_guardian_consent_forms')
    op.drop_table('objectives')
    op.drop_table('meeting_attendees')
    op.drop_table('learning_outcomes')
    op.drop_table('learning_journal_forms')
    op.drop_table('excuse_letter_forms')
    op.drop_table('events')
    op.drop_table('activity_report_forms')
    op.drop_table('password_reset')
    op.drop_table('minutes_of_the_meeting')
    op.drop_table('email_verification')
    op.drop_table('concept_paper_forms')
    op.drop_table('users')
    op.drop_table('student_organizations')
    op.drop_table('signatories')
    op.drop_table('personnel_in_charge_forms')
    op.drop_table('login_attempts')
    op.drop_table('departments')
    # ### end Alembic commands ###
