"""Add indexes to foreign keys and filtered columns

Revision ID: 30749569b97c
Revises: 2f1ab9d0aed0
Create Date: 2026-07-09 18:44:03.651051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30749569b97c'
down_revision = '2f1ab9d0aed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_report_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_report_forms_activity_report_date_submission'), ['activity_report_date_submission'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_report_forms_activity_report_forms_concept_paper_forms_id'), ['activity_report_forms_concept_paper_forms_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_report_forms_activity_report_forms_noted_by'), ['activity_report_forms_noted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_report_forms_activity_report_forms_personnel_in_charge_forms_id'), ['activity_report_forms_personnel_in_charge_forms_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_report_forms_activity_report_forms_prepared_by'), ['activity_report_forms_prepared_by'], unique=False)

    with op.batch_alter_table('activity_report_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_report_items_activity_report_forms_id'), ['activity_report_forms_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_report_items_documentation_id'), ['documentation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_report_items_item_type'), ['item_type'], unique=False)

    with op.batch_alter_table('board_resolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_resolutions_board_resolutions_academic_year'), ['board_resolutions_academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_resolutions_board_resolutions_approved_by'), ['board_resolutions_approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_resolutions_board_resolutions_date'), ['board_resolutions_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_resolutions_board_resolutions_departments_id'), ['board_resolutions_departments_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_resolutions_board_resolutions_events_id'), ['board_resolutions_events_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_resolutions_board_resolutions_prepared_by'), ['board_resolutions_prepared_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_resolutions_board_resolutions_semester'), ['board_resolutions_semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_resolutions_board_resolutions_status'), ['board_resolutions_status'], unique=False)

    with op.batch_alter_table('concept_paper_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_academic_year'), ['concept_paper_forms_academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_approved_by'), ['concept_paper_forms_approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_date'), ['concept_paper_forms_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_departments_id'), ['concept_paper_forms_departments_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_endorsed_by'), ['concept_paper_forms_endorsed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_prepared_by'), ['concept_paper_forms_prepared_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_recommending_approval_by'), ['concept_paper_forms_recommending_approval_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_semester'), ['concept_paper_forms_semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_signed_and_reviewed_by'), ['concept_paper_forms_signed_and_reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_status'), ['concept_paper_forms_status'], unique=False)

    with op.batch_alter_table('documentation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentation_documentation_academic_year'), ['documentation_academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_activity_report_forms_id'), ['documentation_activity_report_forms_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_checked_by'), ['documentation_checked_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_date_of_submission'), ['documentation_date_of_submission'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_departments_id'), ['documentation_departments_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_events_id'), ['documentation_events_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_learning_journal_forms_id'), ['documentation_learning_journal_forms_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_noted_by'), ['documentation_noted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_prepared_by'), ['documentation_prepared_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_semester'), ['documentation_semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentation_documentation_status'), ['documentation_status'], unique=False)

    with op.batch_alter_table('email_verification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_email_verification_users_id'), ['email_verification_users_id'], unique=False)

    with op.batch_alter_table('evaluation_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_forms_documentation_id'), ['documentation_id'], unique=False)

    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_invitations_event_invitations_created_at'), ['event_invitations_created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_invitations_event_invitations_events_id'), ['event_invitations_events_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_events_academic_year'), ['events_academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_events_concept_paper_forms_id'), ['events_concept_paper_forms_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_events_end_date_and_time'), ['events_end_date_and_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_events_semester'), ['events_semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_events_start_date_and_time'), ['events_start_date_and_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_events_status'), ['events_status'], unique=False)

    with op.batch_alter_table('excuse_letter_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excuse_letter_forms_excuse_letter_forms_concept_paper_forms_id'), ['excuse_letter_forms_concept_paper_forms_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excuse_letter_forms_excuse_letter_forms_dean'), ['excuse_letter_forms_dean'], unique=False)
        batch_op.create_index(batch_op.f('ix_excuse_letter_forms_excuse_letter_forms_noted_by'), ['excuse_letter_forms_noted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_excuse_letter_forms_excuse_letter_forms_personnel_in_charge_forms_id'), ['excuse_letter_forms_personnel_in_charge_forms_id'], unique=False)

    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_academic_year'), ['financial_reports_academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_approved_by'), ['financial_reports_approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_audited_and_prepared_by'), ['financial_reports_audited_and_prepared_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_date'), ['financial_reports_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_departments_id'), ['financial_reports_departments_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_events_id'), ['financial_reports_events_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_noted_by'), ['financial_reports_noted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_recommending_approval_by'), ['financial_reports_recommending_approval_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_semester'), ['financial_reports_semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_reports_status'), ['financial_reports_status'], unique=False)

    with op.batch_alter_table('learning_journal_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_journal_forms_learning_journal_forms_concept_paper_forms_id'), ['learning_journal_forms_concept_paper_forms_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_journal_forms_learning_journal_forms_prepared_by'), ['learning_journal_forms_prepared_by'], unique=False)

    with op.batch_alter_table('learning_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_outcomes_concept_paper_forms_id'), ['concept_paper_forms_id'], unique=False)

    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_attendees_minutes_of_the_meeting_id'), ['minutes_of_the_meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_attendees_users_id'), ['users_id'], unique=False)

    with op.batch_alter_table('minutes_of_the_meeting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_academic_year'), ['minutes_of_the_meeting_academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_approved_by'), ['minutes_of_the_meeting_approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_date'), ['minutes_of_the_meeting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_departments_id'), ['minutes_of_the_meeting_departments_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_noted_by'), ['minutes_of_the_meeting_noted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_prepared_by'), ['minutes_of_the_meeting_prepared_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_semester'), ['minutes_of_the_meeting_semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_status'), ['minutes_of_the_meeting_status'], unique=False)

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectives_concept_paper_forms_id'), ['concept_paper_forms_id'], unique=False)

    with op.batch_alter_table('parent_guardian_consent_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_guardian_consent_forms_parent_guardian_consent_forms_concept_paper_forms_id'), ['parent_guardian_consent_forms_concept_paper_forms_id'], unique=False)

    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_password_reset_users_id'), ['password_reset_users_id'], unique=False)

    with op.batch_alter_table('tally_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tally_items_documentation_id'), ['documentation_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_events_id'), ['events_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_users_departments_id'), ['users_departments_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_users_role'), ['users_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_users_student_organization'), ['users_student_organization'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_users_student_organization'))
        batch_op.drop_index(batch_op.f('ix_users_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_users_departments_id'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_events_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))

    with op.batch_alter_table('tally_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tally_items_documentation_id'))

    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_password_reset_users_id'))

    with op.batch_alter_table('parent_guardian_consent_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_guardian_consent_forms_parent_guardian_consent_forms_concept_paper_forms_id'))

    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectives_concept_paper_forms_id'))

    with op.batch_alter_table('minutes_of_the_meeting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_status'))
        batch_op.drop_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_semester'))
        batch_op.drop_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_prepared_by'))
        batch_op.drop_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_noted_by'))
        batch_op.drop_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_departments_id'))
        batch_op.drop_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_date'))
        batch_op.drop_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_approved_by'))
        batch_op.drop_index(batch_op.f('ix_minutes_of_the_meeting_minutes_of_the_meeting_academic_year'))

    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_attendees_users_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_attendees_minutes_of_the_meeting_id'))

    with op.batch_alter_table('learning_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_outcomes_concept_paper_forms_id'))

    with op.batch_alter_table('learning_journal_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_journal_forms_learning_journal_forms_prepared_by'))
        batch_op.drop_index(batch_op.f('ix_learning_journal_forms_learning_journal_forms_concept_paper_forms_id'))

    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_status'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_semester'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_recommending_approval_by'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_noted_by'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_events_id'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_departments_id'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_date'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_audited_and_prepared_by'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_approved_by'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_reports_academic_year'))

    with op.batch_alter_table('excuse_letter_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excuse_letter_forms_excuse_letter_forms_personnel_in_charge_forms_id'))
        batch_op.drop_index(batch_op.f('ix_excuse_letter_forms_excuse_letter_forms_noted_by'))
        batch_op.drop_index(batch_op.f('ix_excuse_letter_forms_excuse_letter_forms_dean'))
        batch_op.drop_index(batch_op.f('ix_excuse_letter_forms_excuse_letter_forms_concept_paper_forms_id'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_events_start_date_and_time'))
        batch_op.drop_index(batch_op.f('ix_events_events_semester'))
        batch_op.drop_index(batch_op.f('ix_events_events_end_date_and_time'))
        batch_op.drop_index(batch_op.f('ix_events_events_concept_paper_forms_id'))
        batch_op.drop_index(batch_op.f('ix_events_events_academic_year'))

    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_invitations_event_invitations_events_id'))
        batch_op.drop_index(batch_op.f('ix_event_invitations_event_invitations_created_at'))

    with op.batch_alter_table('evaluation_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_forms_documentation_id'))

    with op.batch_alter_table('email_verification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_email_verification_users_id'))

    with op.batch_alter_table('documentation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_status'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_semester'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_prepared_by'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_noted_by'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_learning_journal_forms_id'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_events_id'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_departments_id'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_date_of_submission'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_checked_by'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_activity_report_forms_id'))
        batch_op.drop_index(batch_op.f('ix_documentation_documentation_academic_year'))

    with op.batch_alter_table('concept_paper_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_status'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_signed_and_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_semester'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_recommending_approval_by'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_prepared_by'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_endorsed_by'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_departments_id'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_date'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_approved_by'))
        batch_op.drop_index(batch_op.f('ix_concept_paper_forms_concept_paper_forms_academic_year'))

    with op.batch_alter_table('board_resolutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_resolutions_board_resolutions_status'))
        batch_op.drop_index(batch_op.f('ix_board_resolutions_board_resolutions_semester'))
        batch_op.drop_index(batch_op.f('ix_board_resolutions_board_resolutions_prepared_by'))
        batch_op.drop_index(batch_op.f('ix_board_resolutions_board_resolutions_events_id'))
        batch_op.drop_index(batch_op.f('ix_board_resolutions_board_resolutions_departments_id'))
        batch_op.drop_index(batch_op.f('ix_board_resolutions_board_resolutions_date'))
        batch_op.drop_index(batch_op.f('ix_board_resolutions_board_resolutions_approved_by'))
        batch_op.drop_index(batch_op.f('ix_board_resolutions_board_resolutions_academic_year'))

    with op.batch_alter_table('activity_report_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_report_items_item_type'))
        batch_op.drop_index(batch_op.f('ix_activity_report_items_documentation_id'))
        batch_op.drop_index(batch_op.f('ix_activity_report_items_activity_report_forms_id'))

    with op.batch_alter_table('activity_report_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_report_forms_activity_report_forms_prepared_by'))
        batch_op.drop_index(batch_op.f('ix_activity_report_forms_activity_report_forms_personnel_in_charge_forms_id'))
        batch_op.drop_index(batch_op.f('ix_activity_report_forms_activity_report_forms_noted_by'))
        batch_op.drop_index(batch_op.f('ix_activity_report_forms_activity_report_forms_concept_paper_forms_id'))
        batch_op.drop_index(batch_op.f('ix_activity_report_forms_activity_report_date_submission'))

    # ### end Alembic commands ###
