"""Add audit_logs table

Revision ID: 6e6fb6a2aaf8
Revises: 30749569b97c
Create Date: 2026-07-09 20:29:11.181754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6fb6a2aaf8'
down_revision = '30749569b97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_log_timestamp', sa.DateTime(), nullable=False),
    sa.Column('audit_log_user_id', sa.Integer(), nullable=True),
    sa.Column('audit_log_action', sa.String(length=50), nullable=False),
    sa.Column('audit_log_entity_type', sa.String(length=100), nullable=False),
    sa.Column('audit_log_entity_id', sa.Integer(), nullable=True),
    sa.Column('audit_log_changes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_user_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('audit_log_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_audit_log_action'), ['audit_log_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_audit_log_entity_id'), ['audit_log_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_audit_log_entity_type'), ['audit_log_entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_audit_log_timestamp'), ['audit_log_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_audit_log_user_id'), ['audit_log_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_audit_log_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
